### ISSUE TITLE
Single Run

### ISSUE THREAD

**Issue by yihang-xdu** [konst-int-i/healnet#21]
Dear Authors,

Thank you for your outstanding work! When I run the command: python healnet/main.py --mode single_run --config_path config/main_gpu.yml --dataset kirp,  I encountered the following error:  FileNotFoundError: [Errno 2] No such file or directory: '/data1/zyh/healnet-main/data/tcga/omic/tcga_kirp_all_clean.csv.zip'

![image](https://github.com/user-attachments/assets/65bef767-d8b5-4224-922f-0778dc3212ca)

Could you please tell me where I can find or download the tcga_kirp_all_clean.csv.zip file? Thanks!

**Comment by konst-int-i** [comment]
Dear yihang, 

The data should be available using `git-lfs` in the latest release (#22). 

I would recomment: 
* Update the repo: `git pull`
* Install git-lfs if you haven't: `sudo apt-get install git-lfs`
* `git lfs install`
* Pull data `git lfs pull`

The omic data should be pulled to `data/tcga/omic`. 

Let me know if you encounter any other problems running the code!
