### ISSUE TITLE
Issue with *.cvs.zip. The archive is either in an unknown format or damaged

### ISSUE THREAD

**Issue by omniaalwazzan** [konst-int-i/healnet#23]
Thank you very much for sharing your fascinating work. I truly appreciate the effort you put into making the dataset available.

However, I’m encountering an issue when trying to access the zip folders in the dataset folder [omic](https://github.com/konst-int-i/healnet/tree/main/data/tcga/omic). Unfortunately, they all raise the following error: "The archive is either in an unknown format or damaged."

Could you kindly check the dataset folder and see if the files might need to be re-uploaded or corrected? I’d greatly appreciate your help. Thank you once again for your time and support!

Best regards,
Omnia

**Comment by konst-int-i** [comment]
Hi @omniaalwazzan 

Thank you very much for raising this. Can you just confirm two things:
- Did you download the data as given in the readme using `git-lfs pull`? 
- What code are you using to load in the data?

**Comment by omniaalwazzan** [comment]
Hi Konstantin,

Thanks a lot for the prompt response.

I tried both methods: cloning the repository using the Git instructions in the Readme and downloading it directly from GitHub using the green "Code" button. Unfortunately, neither approach made the ZIP folders accessible.

After some experimenting, I managed to read the files inside the zip folders using a custom code snippet. I'm sharing it here in case it helps other Windows users facing a similar issue.
```
import os
import pandas as pd

source_dir = r"C:\healnet\data\tcga\omic"  
target_dir = r"C:\healnet\data\tcga\omic_csv_files"  # Folder to save extracted CSVs

os.makedirs(target_dir, exist_ok=True)
for file_name in os.listdir(source_dir):
    if file_name.endswith('.csv.zip'):  
        zip_path = os.path.join(source_dir, file_name)
        try:
            print(f"Processing: {zip_path}")
            df = pd.read_csv(zip_path, compression='zip')
            output_file_name = file_name.replace('.csv.zip', '.csv')
            output_path = os.path.join(target_dir, output_file_name)
            df.to_csv(output_path, index=False)
            print(f"Saved: {output_path}")
        except Exception as e:
            print(f"Failed to process {zip_path}: {e}")

print("All .csv.zip files have been processed.")
```
Feel free to close this issue if you don't want to add anything to my post, as I solved the problem now; thanks again for your help!

Omnia

**Comment by konst-int-i** [comment]
Hi Omnia, 

Indeed, the zip files were written with the pandas compression, so ideally these are also read in using pandas. This is in line with how it is used throughout this repository, such as the [`TCGADataloader`](https://github.com/konst-int-i/healnet/blob/90459b65a3d4a4ef9fd405671c457b5a1163cc7d/healnet/etl/loaders.py#L298). Although I have no way of testing it on Windows, I would expect the library call to work consistently across operating systems.  

Thanks a lot for raising the issue and let me know if you have any other questions about the code!
